name: Trigger Netlify rebuild for scheduled posts
on: 
    schedule:
        - cron: '0 * * * *'
    workflow_dispatch:
jobs: 
    trigger: 
        name: Trigger a Netlify build
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Run CommitsWithinTime script
              uses: AlexStormwood/CommitsWithinTime@v1.1.12
              id: commitswithintime
              with:
                  hours: 24
            - name: Check CWT output
              run: |
                echo ${{ steps.commitswithintime.outputs.has-new-commits-within-time}}
                echo ${{ steps.commitswithintime.outputs.number-of-commits-within-time}}
                echo ${{ steps.commitswithintime.outputs.total-commits}}
            - shell: bash
              if: ${{ steps.commitswithintime.outputs.has-new-commits-within-time == 'true' }}
              env: 
                NETLIFY_BUILD_HOOK: ${{ secrets. NETLIFY_BUILD_HOOK_URL }}
              run: curl -X POST -d {} "$NETLIFY_BUILD_HOOK"
